name: zacklikejack photography
analytics: {}
content_rating:
  adult: false
github: true
opengraph: {}
author: {}
color:
  lightness: 0.5613265702410896
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
  saturation: 0.4567613835578694
  brandStrength: 0.4372086726215688
  rhythmicContrast: 0.9599506484717015
content: []
layout_spectrum: 0.5
typography_spectrum: 0.5
url: 'https://thegrid.ai/zacklikejack'
