layout_spectrum: 0.8715620529342738
typography_spectrum: 0.6695858814328504
color:
  lightness: 0.7233086323280735
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
  saturation: 0.23901280812882256
  brandStrength: 0.28794098615913777
  rhythmicContrast: 0.6577638895836392
name: pack.zarker.photography
analytics: {}
content_rating:
  adult: false
github: true
opengraph: {}
author:
  url: 'http://zacklikejack.com'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fwww.youtube.com%2Fembed%2F2YVWcXfAPCY&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D2YVWcXfAPCY&image=http%3A%2F%2Fi.ytimg.com%2Fvi%2F2YVWcXfAPCY%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - avatar: {}
      related: []
      publisher:
        url: 'http://youtube.com'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - ''
      description: Uploaded by None on 2017-10-03.
      '@type': VideoObject
      app_links:
        - url: >-
            vnd.youtube://www.youtube.com/watch?v=2YVWcXfAPCY&list=PLaKzcGxazt9-k3ZzHuCpdfknA4axxcLa2&index=1&feature=applinks
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: >-
            vnd.youtube://www.youtube.com/watch?v=2YVWcXfAPCY&list=PLaKzcGxazt9-k3ZzHuCpdfknA4axxcLa2&index=1&feature=applinks
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: >-
            https://www.youtube.com/watch?v=2YVWcXfAPCY&list=PLaKzcGxazt9-k3ZzHuCpdfknA4axxcLa2&index=1&feature=applinks
          type: web
          namespace: ai
        - url: >-
            vnd.youtube://www.youtube.com/watch?v=2YVWcXfAPCY&list=PLaKzcGxazt9-k3ZzHuCpdfknA4axxcLa2&index=1&feature=applinks
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: >-
            vnd.youtube://www.youtube.com/watch?v=2YVWcXfAPCY&list=PLaKzcGxazt9-k3ZzHuCpdfknA4axxcLa2&index=1&feature=applinks
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: >-
            https://www.youtube.com/watch?v=2YVWcXfAPCY&list=PLaKzcGxazt9-k3ZzHuCpdfknA4axxcLa2&index=1
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: >-
            http/www.youtube.com/watch?v=2YVWcXfAPCY&list=PLaKzcGxazt9-k3ZzHuCpdfknA4axxcLa2&index=1
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: >-
            vnd.youtube/www.youtube.com/watch?v=2YVWcXfAPCY&list=PLaKzcGxazt9-k3ZzHuCpdfknA4axxcLa2&index=1
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: >-
        https://www.youtube.com/watch?v=2YVWcXfAPCY&list=PLaKzcGxazt9-k3ZzHuCpdfknA4axxcLa2&index=1
      title: MWZP_Africa
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'http://packzarker.photography/'
title: zack like jack photography
description: ''
